#!/bin/bash
PSQL="psql -X --username=freecodecamp --dbname=number_guess --tuples-only -c"

#READ THE USERNAME
echo "Enter your username:"
read USERNAME
#echo $USERNAME

#SEARCH FOR THE USER IN DATABASE
USER_FROM_DB=$($PSQL "SELECT username FROM users WHERE username='$USERNAME'")
echo $USER_FROM_DB
#IF NOT EXIST


  #SAVE THE NEW NAME AND PROMPT THE WELCOME MESSAGE FOR NEW GAMERS


#ELSE, PROMPT THE WELCOME MESSAGE FOR OLD GAMERS


#GENERATE THE RANDOM BETWEEN (1:1000) NUMBER AND START THE GAME


#WHILE RANDOM NUMBER IS DIFFERENT

  #READ THE NUMBER


  #IF IS NOT AN INTEGER


    #PROMPT THE MESSAGE


  #ELSE


    #IF RANDOM NUMBER IS HIGHER THAN

  
      #READ THE NUMBER AGAIN AND SUM 1 TO THE ATTEMPTS
  

    #ELIF RANDOM NUMBER IS LOWER THAN

  
        #READ THE NUMBER AGAIN AND SUM 1 TO THE ATTEMPTS


    #ELIF RANDOM NUMBER IS EQUAL


        #SUM 1 TO THE ATTEMPTS AND SAVE THE RECORD


#END OF WHILE


#PRINT THE CONGRATULATIONS MESSAGE
#
